const plusButList = document.querySelectorAll('.plus_but');
const minusButList = document.querySelectorAll('.minus_but');
const inputList = document.querySelectorAll('input');
const buttonsList = document.querySelectorAll('.item_but');
const addedList = document.querySelectorAll('.added');
const spanList = document.querySelectorAll('.added .latency_box');
const itemName = document.querySelectorAll('h2');
const priceList = document.querySelectorAll('h3');
const priceHolder = document.getElementById('priceHolder');